### ISSUE TITLE
Remote checking is too strict.

### ISSUE THREAD

**Issue by Freyert** [thlorenz/resolve-git-remote#1]
[This line](https://github.com/thlorenz/resolve-git-remote/blob/master/index.js#L11) is too strict a check. It only allows for users to check if there exists a `github.com` remote. In reality, there are a lot of other domains that could be there.
- Perhaps someone is running a private git server.
- Gitlab?
- GitHub Enterprise

**Comment by thlorenz** [comment]
Open for PRs to fix that :)
